# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='send_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
