# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('web', 'web'), ('programm', 'programm'), ('bots', 'bots'), ('mobile_app', 'mobile_app')], max_length=10)),
            ],
        ),
    ]
