# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='creator',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='descriprion',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='screen_link',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
