# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20170804_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='descriprion',
            new_name='description',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='source_code_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
