# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_auto_20170805_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='project_link',
        ),
    ]
