# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_remove_portfolio_project_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='project_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
