# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_remove_portfolio_project_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
