# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0017_delete_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('creator', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Web', 'Web'), ('Programm', 'Programm'), ('Bots', 'Bots'), ('Mobile App', 'Mobile Apps')], max_length=10)),
                ('description', models.TextField(default=None)),
                ('screen_link', models.CharField(max_length=500)),
                ('source_code_link', models.CharField(blank=True, max_length=300, null=True)),
                ('project_link', models.CharField(blank=True, max_length=300, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
